const Map<String, List<String>> cardNames = {
  'Client Creation': ['Client Name', 'Phone', 'Email', 'Address'],
  'Property Type': ['Name', 'Location'],
  'Create Property': ['Name', 'Size', 'Property Type'],
  'Contract Sign': [
    'Client Selection',
    'Property Selection',
    'Contract Start Date',
    'Contract End Date',
    'Amount',
    'Tax/Vat %',
    'Tax/Vat Amount',
    'Discount %',
    'Discount Amount',
  ],
  'Contract History': [],
  'Receive Amount': [],
  'Ledger Balance': [],
  'Coming Soon': [],
  'Coming Soon.': [],
};
